### ISSUE TITLE
Mismatched types with addition

### ISSUE THREAD

**Issue by jonny7** [vapor/leaf#107]
Just trying to create a new url with pagination like so

```
href="/list?page=#(currentPage - 1)&size=#(pageSize)"
```

My Struct context declares these as `Int`. But when I add or subtract from the variable the result is a `Double`. Just spoke to Tim about it and he said to raise it.

**Comment by mcdappdev** [comment]
Related to https://github.com/vapor/leaf/issues/101

**Comment by jonny7** [comment]
@mcdappdev Missed that ticket! 😄

**Comment by mcdappdev** [comment]
All good! Just wanted to make sure there was a note linking them together :)
