### ISSUE TITLE
Update Package.swift for Vapor 3

### ISSUE THREAD

**Issue by andreasley** [vapor/leaf#116]
First: Congrats on the release of Vapor 3!

Unfortunately, Leaf's current `Package.swift` doesn't work with the non-rc version of Vapor 3. When running `vapor update`, the command `swift-package` never returns (probably goes in circles trying to resolve dependencies).

**Comment by 0xTim** [comment]
How are you trying to pull in Leaf? It should work like so https://github.com/raywenderlich/vapor-til/blob/master/Package.swift#L9

**Comment by andreasley** [comment]
You're absolutely right, `from: "3.0.0-rc"` works. Thanks! 
I'll never get used to SwiftPM.

The [docs](https://docs.vapor.codes/3.0/leaf/getting-started/) suggested the following (which failed):
```
.package(url: "https://github.com/vapor/leaf.git", .branch("beta"))
```
I've then tried the following, which runs forever: 
```
.package(url: "https://github.com/vapor/leaf.git", from: "3.0.0")
```
So I think updating the docs would be a good thing (and eventually a Leaf 3 release when it's ready).

**Comment by tanner0101** [comment]
Release PR is up now #122. I will make sure the docs get updated, too. Thanks :)
