### ISSUE TITLE
Bug Running Leaf With --env production Enabled

### ISSUE THREAD

**Issue by joeblau** [vapor/leaf#117]
I've created a sample project to save the work of building sample:

https://github.com/joeblau/vapor-leaf-bug

```sh
git clone git@github.com:joeblau/vapor-leaf-bug.git
cd vapor-leaf-bug
swift build
# Fails
swift run Run --env production

# Fails too
./.build/x86_64-apple-macosx10.10/release/Run --env production
```

Go to: http://localhost:8080/ then: http://localhost:8080/docs

They will either both be the docs endpoint or the landing endpoint or randomly switch.

The same problem is. happening on my production server on https://www.gitignore.io

https://www.gitignore.io/
https://www.gitignore.io/docs

**Comment by joeblau** [comment]
Ah if that's the bug, then the issue is pretty straight forward.  The [TemplateData](https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Data/TemplateData.swift#L3) class doesn't conform to the `Hashable` protocol and [TemplateRenderer](https://github.com/vapor/template-kit/blob/master/Sources/TemplateKit/Pipeline/TemplateRenderer.swift#L45) relying on ".hashValue" for the hashing key.

**Comment by DanielsCode** [comment]
Looking forward to see a bugfix.

**Comment by tanner0101** [comment]
vapor/template-kit#25 has been fixed and closed. Thanks for reporting!
