### ISSUE TITLE
Path "Resources/Views" not found

### ISSUE THREAD

**Issue by xGoPox** [vapor/leaf#129]
Hello 👋,

I just built the latest Vapor template and the folders struct is now `Sources/` and - I guess - not anymore `Resources/` which cause the `LeafProvider` not to find the correct path.

Should I do a pull request and change the `LeafProvider.swift` ?

**Comment by 0xTim** [comment]
@xGoPox which template have you started with? If you started with the API template then you can just create the directories yourself

**Comment by 0xTim** [comment]
If you do `vapor new Foo --template=web` that should have everything you need

**Comment by wendyliga** [comment]
@xGoPox make sure you use `vapor xcode`, vapor will generate `mac xcodeproj`, so the executable can contains resources outside compiled code

**Comment by 0xTim** [comment]
`vapor Xcode` has been replaced by `open Package.swift` which uses Xcode 11's built in SwiftPM support. You will need to set your custom working directory though

**Comment by wendyliga** [comment]
@0xTim using `open Package.swift`, will make `Resources` and `Public` not copied into build folder hence got this error?

**Comment by 0xTim** [comment]
Yeah you need to set the custom working directory for the Run scheme to your projects local directory

**Comment by wendyliga** [comment]
that's make sense

**Comment by 0xTim** [comment]
I'll close this issue as well as the original issue is stale and I'm assuming fixed

**Comment by PsN-1** [comment]
@0xTim "You will need to set your custom working directory though"
how or where I set this?? cause when I run the server through the terminal (vapor run) it works just fine
But when I try on Xcode, it can't find the routes.

thx

**Comment by 0xTim** [comment]
@PsN-1 see https://www.timc.dev/posts/custom-working-directory/
