### ISSUE TITLE
Issue: Vapor Leaf not working with MathJax

### ISSUE THREAD

**Issue by marc-medley** [vapor/leaf#133]
[MathJax](https://www.mathjax.org/) is a JavaScript display engine for mathematics that works in all browsers. However, the [Vapor Leaf](https://github.com/vapor/leaf) and [MathJax](https://www.mathjax.org/) combination does not render math expressions correctly.

The example code for this issue is in the GitHub [VaporExamplesLab/issue-vapor-leaf-mathjax](https://github.com/VaporExamplesLab/issue-vapor-leaf-mathjax) repository.

### Steps to reproduce

``` bash
vapor new issue-vapor-leaf-latex --web
cd issue-vapor-leaf-latex
vapor update -y
```

_routes.swift_ (Add `math` test route.)

``` swift
// :ADD: math
router.get("math") { req -> Future<View> in
    return try req.view().render("math")
}
```

_Resources/Views/base.leaf_ (Add MathJax to existing base.leaf.)

``` html
<!DOCTYPE html>
<html>
<head>
	<title>#get(title)</title>
	<link rel="stylesheet" href="/styles/app.css">
</head>
<body>
    #get(body)
    
    <!-- MathJax: https://www.mathjax.org/#gettingstarted -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
</body>
</html>
```

_Resources/Views/math.leaf_ (Added leaf file.)

``` html
#set("title") {Math Leaf Page}

#set("body") {
	<p>Two equations: \(A^T_S = B\) and \(\sqrt{ab}\).</p>
    <p>\[A^T_S = B\]  </p>
    <p>\[\sqrt{ab}\]  </p>
}

#embed("base")
```

### Expected behavior

_Public/MathExample.html_ (working example)

``` html
<!DOCTYPE html>
<html>
<head>
  <title>MathExample</title>
</head>

<body>

    <p>Two equations: \(A^T_S = B\) and \(\sqrt{ab}\).</p>
    <p>\[A^T_S = B\]  </p>
    <p>\[\sqrt{ab}\]  </p>

    <!-- MathJax: https://www.mathjax.org/#gettingstarted -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
</body>
</html>
```
![ExpectedOutput](https://user-images.githubusercontent.com/15098151/54093000-f09fe980-434f-11e9-8bea-efd9ba5a3a88.png)

### Actual behavior

![ActualOutput](https://user-images.githubusercontent.com/15098151/54092986-d239ee00-434f-11e9-86a9-ccc3e64a7813.png)

Resulting source as seen in browser:

``` html
\).</p>
    <p>\[A^T_S = B\]  </p>
    <p>\[\sqrt{ab}\]  </p>
}

<!DOCTYPE html>
<html>
<head>
	<title>Math Leaf Page</title>
	<link rel="stylesheet" href="/styles/app.css">
</head>
<body>
    
	<p>Two equations: \(A^T_S = B\) and \(\sqrt{ab
    
    <!-- MathJax -->
    <!-- https://www.mathjax.org/#gettingstarted -->
    <!-- config=TeX-MML-AM_CHTML (standard) | config=TeX-AMS_SVG (SVG)-->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
    <!-- script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_SVG' async></script -->
</body>
</html>
```

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS High Sierra 10.13.6, Xcode 10.1, Swift 4.2

**Comment by marc-medley** [comment]
The conflict appears related to `{` and `}`. 

A manual edit to from `\sqrt{ab}` to `\sqrt&#x007b;ab&#x007d;` in the _math.leaf_ file will result in a correct rendering.  However, this manual edit seems generally unpractical for workflows which use various tools to generate html math formula snippets.  The math snippets have  `{` and `}` characters instead of hex encoded entities.

**Comment by joscdk** [comment]
@marc-medley usually stuff like this can also be prevented by escaping `}` e.g.:

```
#set("body") {
    Something \}
}
```

**Comment by marc-medley** [comment]
@joscdk  Thanks for pointing out a work around.  Ended up being two tries to get right ...

Apparently escaping both `{` and `}` does not quite work. Leaf does not break; however, the math expression does not render.

``` html
#set("body") {
<p>Two equations: \(A^T_S = B\) and \(\sqrt\{ab\}\).</p>
    <p>\[A^T_S = B\]  </p>
<p>\[\sqrt\{ab\}\]  </p>
}
```

![EscapedBothOutput](https://user-images.githubusercontent.com/15098151/54094165-09160100-435c-11e9-8ced-21c9c2c66865.png)

Apparently _escaping only the **left bracket**_ `\}` does work:

``` html
#set("body") {
<p>Two equations: \(A^T_S = B\) and \(\sqrt{ab\}\).</p>
    <p>\[A^T_S = B\]  </p>
<p>\[\sqrt{ab\}\]  </p>
}
```

![EscapedLeftOutput](https://user-images.githubusercontent.com/15098151/54094170-0fa47880-435c-11e9-9f05-78555c45588c.png)

---

It would be helpful if this Leaf limitation and _left bracket escaping_ `\}` workaround were _clearly (even **boldly**)_ stated in the [Leaf documentation](https://docs.vapor.codes/3.0/leaf/overview/)

**Comment by marc-medley** [comment]
@joscdk  BTW, thanks for the forum link regarding a proposed solution. I added feedback and a syntax alternative there for consideration. See: https://forums.swift.org/t/pitch-new-leaf-body-syntax/18188/14

**Comment by 0xTim** [comment]
Closing as the syntax is different in Vapor 4 and should no longer be an issue
