### ISSUE TITLE
Leaf failing with Swift 5.

### ISSUE THREAD

**Issue by kylebrowning** [vapor/leaf#135]
It appears that swift 5 has broken leaf in some way.

With Xcode 10.2, and Swift 5, build and run the web template, then goto your localhost:8080 to see the following error.

```json
{"error":true,"reason":"Unsupported key type (\/Users\/kylebrowning\/work\/swift\/test-leaf\/Resources\/Views\/welcome.leaf line: 0 column: 1 range: 1..<26)"}
```

Steps to reproduce:

```
kylebrowning at Kyles-Mac-mini in ~/work/swift
$ vapor new test-leaf --template=web
Cloning Template [Done]
Updating Package Name [Done]
Initializing git repository [Done]

                                            **
                                          **~~**
                                        **~~~~~~**
                                      **~~~~~~~~~~**
                                    **~~~~~~~~~~~~~~**
                                  **~~~~~~~~~~~~~~~~~~**
                                **~~~~~~~~~~~~~~~~~~~~~~**
                               **~~~~~~~~~~~~~~~~~~~~~~~~**
                              **~~~~~~~~~~~~~~~~~~~~~~~~~~**
                             **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                             **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                             **~~~~~~~~~~~~~~~~~~~~~++++~~~**
                              **~~~~~~~~~~~~~~~~~~~++++~~~**
                               ***~~~~~~~~~~~~~~~++++~~~***
                                 ****~~~~~~~~~~++++~~****
                                    *****~~~~~~~~~*****
                                       *************
                              
                              _       __    ___   ___   ___
                             \ \  /  / /\  | |_) / / \ | |_)
                              \_\/  /_/--\ |_|   \_\_/ |_| \
                                a web framework for Swift

                          Project "test-leaf" has been created.
                   Type `cd test-leaf` to enter the project directory.
                 Use `vapor cloud deploy` to host your project for free!
                                          Enjoy!


kylebrowning at Kyles-Mac-mini in ~/work/swift
$ cd test-leaf/

kylebrowning at Kyles-Mac-mini in ~/work/swift/test-leaf on master
$ vapor xcode
Generating Xcode Project [Done]
Select the `Run` scheme to run.
Open Xcode project?
y/n> y
Opening Xcode project...

kylebrowning at Kyles-Mac-mini in ~/work/swift/test-leaf on master
```

Then build and run, goto http://localhost:8080

Falling back to Swift 4.2 seems to alleviate this issue.

**Comment by mcdappdev** [comment]
I’m seeing the same problem.

**Comment by mcdappdev** [comment]
Did some investigating, looks like it’s getting caught up on Line 17 of Var.swift. It can’t convert the token to a string, for some reason.

**Comment by foscomputerservices** [comment]
> Did some investigating, looks like it’s getting caught up on Line 17 of Var.swift. It can’t convert the token to a string, for some reason.

I too looked into this earlier today.  Some strings that were encoded in Data were not convertible to String.  I thought maybe they were in other encodings (.utf16, .ascii, etc.), but I tried converting them by hand in the debugger and that didn't work.

For me the errors were decoding the string names from #set() statements.  I found it interesting that on the 1st pass of the leaf file things seemed to work, but when I refreshed the page, some failed.  Caching?

**Comment by mcdappdev** [comment]
All of that is consistent with what I tried/discovered as well.

**Comment by calebkleveter** [comment]
So I guess this is related to strings in Swift 5 using UTF-8 encoding by default.

**Comment by tanner0101** [comment]
I think this should fix it: https://github.com/vapor/template-kit/pull/46

**Comment by XbladeSub** [comment]
Try to delete all whitespaces from your broken .leaf file - it can be helpfull
