### ISSUE TITLE
Question: Vapor 4 support

### ISSUE THREAD

**Issue by dmDevelop** [vapor/leaf#142]
Hi,

I just wanted to know, what is the status of Leaf supporting Vapor 4 and if Leaf templating engine will remain in Vapor or will development lead to some other templating engine?

Also, since some recent activities were on master branch, i would like to know how to include Leaf in Vapor 4.

Thank you!

**Comment by E13Lau** [comment]
use .package(url: "https://github.com/vapor/leaf.git", from: "4.0.0-rc")

**Comment by 0xTim** [comment]
Leaf is currently being heavily worked on, most of the work is done in the vapor/leaf-kit repository. As @E13Lau said, that's the correct way to use Leaf for Vapor 4
