### ISSUE TITLE
Vapor 4b1: Lexer Error: # as href value

### ISSUE THREAD

**Issue by hfhbd** [vapor/leaf#145]
Hey, 

with leaf 4.0.0-beta.1 it is not possible to use a # as an href value.

LexerError(line: 1, column: 10, name: "Resources/Views/test.leaf", reason: LeafKit.LexerError.Reason.invalidTagToken("\""), lexed: [raw("<!DOCTYPE html>\n<a href=\""), tagIndicator])

Content of test.leaf:
`<!DOCTYPE html>
<a href="#">test</a>`

**Comment by tdotclare** [comment]
Closed in LeafKit-1.0.0tau
