### ISSUE TITLE
Allow emoji tokens 

### ISSUE THREAD

**Issue by tanner0101** [vapor/leaf#15]
`Leaf.token = "🍃"`

```
Hello, 🍃(name)
```

This would be so cool.

**Comment by rugaard** [comment]
Wouldn't this be extremely annoying for users of other OS (Windows, Ubuntu etc)? And what about users coding directly in Vim? Can you use Emoji's there? :)

**Comment by tannernelson** [comment]
It wouldn't be the default! I'm just saying I personally would like to set it as an Emoji.

**Comment by BrettRToomey** [comment]
@rugaard Yes, you can use emojis in vim.

@tanner0101 closing this for now. Feel free to reopen.
