### ISSUE TITLE
ForLoop Issue

### ISSUE THREAD

**Issue by diuming** [vapor/leaf#150]
Vapor: 4.0.0-beta.3.1
Leaf: 4.0.0-beta.2

Route.swift
---
```
func leafRoutes(_ app: Application) throws {
    app.get("leaf", "forloop") { (request) -> EventLoopFuture<View> in
        return request.view.render("ForLoop.leaf", ["band": ["A", "B", "C"]])
    }
}
```

Error: [ ERROR ] for loops expect single expression, 'name in names'
---
```
<!DOCTYPE html>
<head>
</head>
<html>
    <body>
        <ul>
        #for (member in band) {
            <li>#(member)</li>
        }
        </ul>
    </body>
</html>
```

Error: [ ERROR ] for loops require a body
---
```
<!DOCTYPE html>
<head>
</head>
<html>
    <body>
        <ul>
        #for(member in band)
            <li>#(member)</li>
        #endfor
        </ul>
    </body>
</html>
```

**Comment by wall1350** [comment]
You may try this, I just add  " : " , then the error is disappearing.

<!DOCTYPE html>
<head>
</head>
<html>
    <body>
        <ul>
        #for(member in band):
            <li>#(member)</li>
        #endfor
        </ul>
    </body>
</html>

**Comment by wall1350** [comment]
You may try this, I just add  " : " , then the error is disappearing.

```
<!DOCTYPE html>
<head>
</head>
<html>
    <body>
        <ul>
        #for(member in band):
            <li>#(member)</li>
        #endfor
        </ul>
    </body>
</html>
```

**Comment by diuming** [comment]
@wall1350 thanks
it works!
