### ISSUE TITLE
Cache `isEnabled` not settable from Vapor

### ISSUE THREAD

**Issue by deze333** [vapor/leaf#154]
In Vapor's `configure.swift` trying to **disable Leaf cache** for development purposes.

**Problem 1:**

Since `.leaf` is a get-only property not much can be done to configure it:

```swift
app.views.use(.leaf)
let _ = app.leaf.cache.isEnabled // yes, can get
app.leaf.renderer.cache.isEnabled = false // no, can't set, error "get only property"
```

**Problem 2:**

Example given in "What’s New in Vapor 4":

```swift
app.leaf.configuration = LeafConfiguration(...)
```

doesn't work, neither does something like this:

```swift
app.leaf.configuration = LeafConfiguration(rootDirectory: "Resources/Views")
```

**Comment by tanner0101** [comment]
Oops. This should definitely be settable, thanks for reporting.
