### ISSUE TITLE
Bug: Need escaping # in Leaf 

### ISSUE THREAD

**Issue by anmolrajpal** [vapor/leaf#157]
After following up in Discord conversation to my [question](https://stackoverflow.com/questions/60513584/server-side-swift-navbar-toggle-not-working-in-vapor-4-leaf-bootstrapl), I'm opening this issue here until it's solved. 

My Scenario: Bootstrap NavBar Toggle -> data-target="#navbar-collapse" results in empty (data-target) in debugger.

**Comment by tanner0101** [comment]
Related to https://github.com/vapor/leaf-kit/issues/16

**Comment by tanner0101** [comment]
cc @loganwright

**Comment by tdotclare** [comment]
Closed in LeafKit-1.0.0tau
