### ISSUE TITLE
String containing space is not completely rendered

### ISSUE THREAD

**Issue by ozzyq7** [vapor/leaf#162]
When trying to render a String divided with space e.g. `FirstPart SecondPart`, then only `FirstPart` is rendered. 

The String is loaded into a variable `name` correctly, but when I am trying prepopulate a text field with `<input type="text" value=#(name) name="name" class="form-control" id="name"/>` then only `FirstPart` is displayed.

**Comment by tanner0101** [comment]
You should have quotes around `value` for example:

```leaf
value="#(name)"
```

Not sure if that's the problem though.

**Comment by ozzyq7** [comment]
Yes, that was the problem. Sorry, my bad. Thank you very much, Tanner!
