### ISSUE TITLE
Nested directories

### ISSUE THREAD

**Issue by GildedHonour** [vapor/leaf#171]
In the documention it's not shown how to use templates when they are, including a layout, located all in different, possibly nested in multiple levels, directories.

How?

**Comment by tdotclare** [comment]
@GildedHonour 

For the current Leaf4/LeafKit1rc builds, whatever is specified in Vapor as the `viewDirectory` is the root directory Leaf will check for resources. Nesting as normal in that directory is all accessible.

Accessing files outside of that directory is feasible by customizing the configuration for `LeafSources` (app.leaf.sources) prior to starting the application:

* You can configure a single source with a higher, "sandbox" path that will allow access outside of the configured view directory (eg, sandbox of "/www/app" and view directory of "/www/app/Resources/Views" will always scope relative template requests to the view directory, but allows access to anything inside "/www/app" by absolute or relative pathing)
or
* You can register additional `LeafSource` objects that will be searched in order - eg, a source for "/www/app/Resources/Views", a source for "/www/app/Admin/Views", etc etc.

If you're unconcerned about global file access, the following approximate code configuring Leaf before starting would allow full access:
```swift
app.leaf.sources = .singleSource(fileio: app.fileio,
                                 limits: .default,
                                 sandboxDirectory: "/",
                                 viewDirectory: app.directory.viewsDirectory)
```

**Comment by GildedHonour** [comment]
Ok, thx. But aside from that, this code

```

func routes(_ app: Application) throws {
    app.get { req in
        req.view.render("page/index", [
            "var1": "var111"
        ])
    }
```

 throws **LeafError.Reason.noTemplateExists("page/index"))**  always.

A file "Resources/Views/page/index.leaf" exists.

I've tried different combinations: with/without "/", capital/lower case......

**Comment by tdotclare** [comment]
If you're building/executing inside Xcode, you will need to set a custom working directory in your build schema to point at your project directory, as otherwise it defaults to the derived data directory for Xcode builds.

**Comment by GildedHonour** [comment]
Thansk, all works.
