### ISSUE TITLE
error with unsupported expression?

### ISSUE THREAD

**Issue by diuming** [vapor/leaf#174]
```
#export("auto-refresh", "<meta http-equiv="refresh" content="300">")
```

[ ERROR ] unsupported expression, expected 2 or 3 components: [stringLiteral("<meta http-equiv="), variable(refresh), stringLiteral(" content="), constant(300), stringLiteral(">")] [request-id: AB2A73DA-55D4-4C72-9699-A8D8ECD705A3]

**Comment by tdotclare** [comment]
Your parameter has unescaped quotes.

**Comment by diuming** [comment]
release?
