### ISSUE TITLE
Can't Access Leaf files in final Docker build

### ISSUE THREAD

**Issue by dylanreich** [vapor/leaf#175]
(Vapor 4)
I am unable to render Leaf web pages after making a Docker build.

in my `configure.swift` I have

```
app.leaf.configuration.rootDirectory = projectFolder

app.leaf.sources = .singleSource(NIOLeafFiles(fileio: app.fileio,
    limits: .default,
    sandboxDirectory: projectFolder,
    viewDirectory: viewsFolder))
```

 and when running the project from Xcode I can see my web pages, but when compiling a Docker build and running that, when I try to load a web page I get

`[ ERROR ] LeafError(file: "/build/.build/checkouts/leaf-kit/Sources/LeafKit/LeafSource/LeafSources.swift", function: "searchSources(t:on:s:)", line: 76, column: 69, reason: LeafKit.LeafError.Reason.noTemplateExists("index")) [request-id: 4D5D6F6A-9C72-4D49-9B20-885FA5D08874]`

I think it may have something to do with getting the Leaf files properly copied and exposed. Here's the line in my Dockerfile I've been messing with that I modified from a snippet I found:

`COPY --from=build --chown=vapor:vapor /build/Views /app/Views`

Here are my definitions for projectFolder and viewsFolder:

```
internal var projectFolder: String {
    let folder = #file.split(separator: "/").dropLast(3).joined(separator: "/")
    return "/" + folder + "/"
}

internal var viewsFolder: String {
    return projectFolder + "Views/"
}
```

**Comment by tdotclare** [comment]
`#file` is going to be hardcoded at build time to the build folder, so you can't use that if you want to copy from the build location. your configuartion as is would be trying to access `/build/Views` -  I'd advise ensuring your app configuration has `application.directory.workingDirectory` set to "/app" and use that as the base.
 
```swift
app.leaf.sources = .singleSource(NIOLeafFiles(fileio: app.fileio,
    limits: .default,
    sandboxDirectory: application.directory.workingDirectory,
    viewDirectory: application.directory.workingDirectory + "Views/"))
```

**Comment by dylanreich** [comment]
That worked as-is when building for Docker, thank you!
