### ISSUE TITLE
Custom tags in 4.0.0-tau.1

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/leaf#179]
Please can you specify how to create custom tags in tau version

**Comment by apps4everyone** [comment]
@Igor-Palaguta maybe this will help you? `https://theswiftdev.com/custom-leaf-tags-in-vapor-4/`

**Comment by Igor-Palaguta** [comment]
@apps4everyone Thank you, let me check

**Comment by 0xTim** [comment]
Custom tags for Leaf 4 are added in this PR - https://github.com/vapor/docs/pull/564

Tau is becoming a separate rendering engine so that will have it's own docs
