### ISSUE TITLE
Leaf Tau style Change Of File Type

### ISSUE THREAD

**Issue by bcousins** [vapor/leaf#182]
At the outset: I appreciate the direction Vapor has gone in separating Tau and Leaf. I appreciate that they're seperate projects and I appreciate where they're going are two different places, however:

I believe that there should be a way in Vapor's Leaf to adjust the file type, particularly for XCode development purposes. .leaf files, as we know, do not have the ability to inherit a colour scheme, and, while this is all well and good for experienced devs, sometimes, you can miss things, and I feel that the ability to adjust the file type to be .html would benefit the project.

I don't believe that this is possible with the default implementation of Leaf.

I originally posted this on the work account by accident, like a pleb. If someone who maintains the project could delete #181, I'd be grateful.

**Comment by 0xTim** [comment]
I don't think that allowing renaming of the extension to work around IDE deficiencies is a good idea. It's likely to lead to confusion on projects and misleading. Leaf files show following the `.leaf` extension.

I'm working on a Leaf VSCode syntax highlighter and there appears to be a workaround to make Leaf files work as HTML in Xcode as per the [3.0 docs](https://docs.vapor.codes/3.0/leaf/getting-started/#xcode).
