### ISSUE TITLE
array count tag is absent in Leaf 4

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/leaf#184]
In Leaf 3 count tag worked for arrays, but now it is absent in Leaf 4
```
      #if(count(images) > 0):
      #count(images) images
      #else:
      No images
      #endif
```

Also probably leaf should fail in case if tag is not found

Leaf version
"4.0.0-rc.1.4"

**Comment by 0xTim** [comment]
Count has been added in vapor/leaf-kit#79 and is just waiting for a review before being tagged
