### ISSUE TITLE
Rationale behind using '#' character?

### ISSUE THREAD

**Issue by lmcd** [vapor/leaf#187]
I just started using Leaf for the first time. I have an API with a single HTML landing page. In order to reduce complexity and security attack surface, I'm not using the `FileMiddleware`, and am inlining some simple CSS and JavaScript. I noticed immediately that I'm forced to constantly escape things all over the place to get templates to work (like CSS colours).

Since it's still early days for Leaf, and we'd all love Vapor to gain the major traction it deserves, would the core team be interested in revising the syntax to allow for easier adoption? Personally I enjoy the Twig syntax  -e.g. {{ hello }}

**Comment by 0xTim** [comment]
The Leaf syntax was discussed on the forums a couple of years ago here - https://forums.swift.org/t/pitch-new-leaf-body-syntax/18188

We can revisit the syntax for the next major version, but it's not possible to change without a major breaking change.

As an aside, if you're concerned about your security attack surface you should be blocking inline CSS and JS with a CSP header and loading it from an external trusted source (or your own domain)

**Comment by lmcd** [comment]
My use case necessitates the server have control over the CSS output, and we're talking a barebones stylesheet of just a few kb. Adding a whole new server/deployment workflow for one 2kb CSS file adds complexity I'm trying to avoid.

How a stylesheet gets served is beyond the point I was trying to make: Leaf, by design makes it difficult to serve the kind of templates its presumably intended to serve - HTML ones.

This issue was designed to serve as a discussion point around changing the syntax in a future major version. I wasn't suggesting we put out a minor point update with a major breaking change. There was potentially also discussion to be had around avoiding false positives 🤷‍♂️

**Comment by 0xTim** [comment]
Sorry, didn't mean to come across like nothing was up for discussion! Rushing through issues is always fun! 😅 

My suggestion would be to open an issue on the Swift forums to discuss new syntax for Leaf, that's a better place to have those discussions. Additionally, once #128 is solved, that should make inline CSS much easier
