### ISSUE TITLE
Add leaf format support in Xcode

### ISSUE THREAD

**Issue by Kyle-Ye** [vapor/leaf#189]
Simply run a demo app once with leaf Exported Type Identifiers added, then we can get html render in Xcode with leaf format
<img width="1440" alt="截屏2021-03-08 17 05 16" src="https://user-images.githubusercontent.com/43724855/110299464-a7fb9380-8030-11eb-8d16-773178422b3e.png">
<img width="1440" alt="截屏2021-03-08 17 07 33" src="https://user-images.githubusercontent.com/43724855/110299588-d1b4ba80-8030-11eb-927d-cba92756dd9e.png">

**Comment by 0xTim** [comment]
There's also https://github.com/OmranK/LeafSyntaxHighlighter to help with this.

Closing this issue as there are a couple of solutions for Xcode
