### ISSUE TITLE
Questions about syntax highlighting and formatting for leaf

### ISSUE THREAD

**Issue by CainLuo** [vapor/leaf#202]
Regarding the syntax highlighting and formatting of leaf, I found a folder named leaf-pygment in the docs file, what is this used for? And about editing the leaf file, so far I only found Visual Studio Code has the corresponding plug-in to use, but there are some small problems in formatting the leaf code, is there a plugin for Xcode for leaf code highlighting and formatting?

**Comment by 0xTim** [comment]
The `leaf-pygment` directory contains a very simple (and out of date) parser for syntax highlighting for the docs when they're generated.

What issues do you have when using one of the Leaf plugins for VSCode? Xcode is far more problematic as there's no plugin and it can cause issues when trying to make it work with HTML as well

**Comment by CainLuo** [comment]
> The `leaf-pygment` directory contains a very simple (and out of date) parser for syntax highlighting for the docs when they're generated.
> 
> What issues do you have when using one of the Leaf plugins for VSCode? Xcode is far more problematic as there's no plugin and it can cause issues when trying to make it work with HTML as well

Oh, it turns out that leaf-pygment is used to highlight code syntax, but I found it didn't work. I found that it didn't automatically format HTML pages when I tried to write them with leaf, much to my chagrin, so I was looking for a leaf formatting plugin, but to my surprise VSCode actually has a plugin that provides leaf formatting, called vapor-leaf, but to my dismay the plugin isn't very smart.

**Comment by 0xTim** [comment]
leaf-pygment is only for syntax highlighting when being rendered in a client such as a web browser. It's not designed for an IDE. The other VSCode extension is https://marketplace.visualstudio.com/items?itemName=Francisco.html-leaf

For issues with the extensions you'll need to raise an issue on their GH repo as they're community projects rather than Vapor projects
