### ISSUE TITLE
Bugs on Xcode 13.3

### ISSUE THREAD

**Issue by underthestars-zhy** [vapor/leaf#204]
### Describe the bug

 'self' refers to the method 'LeafKeyword.self', which may be unexpected

### To Reproduce

Just add leaf package

1. Add package with configuration '4.1.5.'
3. See error

### Environment

* Vapor Framework version: 4.55.0
* Xcode: 13.3 beta
* OS version: beta

**Comment by 0xTim** [comment]
Closing in favour of vapor/leaf-kit#99
