### ISSUE TITLE
Being able to loop over arrays that are the results of function calls

### ISSUE THREAD

**Issue by Frizlab** [vapor/leaf#206]
**Is your feature request related to a problem? Please describe.**
I tried to do this:
```
#for(status in entryStatuses()):
  some stuff
#endfor
```
Where `entryStatuses` is a custom leaf tag (which has been tested to work and return an array).

However I got an error: `for loops expect single expression, 'name in names'`

**Describe the solution you'd like**
It’d be great to have the array on which we want to loop be able to be any expression, not a simple variable.

**Describe alternatives you've considered**
I am currently sending the array via the context instead of the custom leaf tag I created.

**Additional context**
None.

**Comment by 0xTim** [comment]
Closing in favour of vapor/leaf-kit#81
