### ISSUE TITLE
[4.2.1] Fails to build with: Value of type '[CodingKey?]' has no member 'compacted'

### ISSUE THREAD

**Issue by gh123man** [vapor/leaf#214]
### Describe the bug

Leaf `4.2.1` fails to build with the error:
```
Value of type '[CodingKey?]' has no member 'compacted'
```

on this line: https://github.com/vapor/leaf/blob/main/Sources/Leaf/LeafEncoder.swift#L81
Introduced in: https://github.com/vapor/leaf/commit/04f262edbee143cdfefc5b26cef704913712e16c

Seems like this may be an extension that was not included? 

### To Reproduce

1. Create a new project
2. include leaf
3. try to build 

### Expected behavior

Should build out of the box.

### Environment

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

### Additional context

Workaround: revert back to `4.2.0`.

**Comment by 0xTim** [comment]
@gh123man can you run a package update? We probably missed a dependency bump somewhere

**Comment by gh123man** [comment]
@0xTim Looks like a `swift package update` fixed it. Thanks 👍
