### ISSUE TITLE
Xcode syntax highlighting

### ISSUE THREAD

**Issue by landsman** [vapor/leaf#226]
### Describe the bug 

Maybe I missed something, but in documentation is no mention how to make it work.

### To Reproduce

I created project by `vapor new vapor-framework` and allow leaf in interactive terminal. So it's a result of template project.

![Screenshot 2023-07-05 at 11 55 02](https://github.com/vapor/leaf/assets/3184228/a5ade444-c66a-471e-8dfc-8288d3479eb6)

### Expected behavior

I would expect that in this doc: https://docs.vapor.codes/leaf/getting-started/ will be note about xcode extension or link to tutorial how to make work syntax highlighting in Xcode.

I found some unofficial projects like https://github.com/OmranK/VaporLeafPlugIn, but this should be under "official hood", repository for sure, at least link in doc 🙏 

### Environment

* Vapor Framework version: 4.77.0
* Vapor Toolbox version: 18.7.1
* OS version: macOS 13.4

**Comment by 0xTim** [comment]
Xcode syntax highlighting is probably out of scope for the project since it's so hard to write a decent extension for Xcode. We recommend sticking to VSCode instead
