### ISSUE TITLE
#() is working and #raw(){#feature} throwing an error

### ISSUE THREAD

**Issue by dhamukrish** [vapor/leaf#30]
I am not understanding how this works or not sure it's a bug. Please advise.

`<a href="#(link)#()features">Features</a>`
`<a href="#(link)#raw() {#features}">Features</a>`
No error

Below throws error when no space between `raw()` and `{`
`<a href="#(link)#raw(){#features}">Features</a>`
Uncaught Error: ParseError.expectedOpenParenthesis. Use middleware to catch this error and provide a better response. Otherwise, a 500 error page will be returned in the production environment.

**Comment by LoganWright** [comment]
@dhamukrish were you able to resolve this? I believe you just need a space from `) {`. Let me know if that doesn't resolve it.
