### ISSUE TITLE
Leaf template does not render when bracket is on the next line

### ISSUE THREAD

**Issue by neospirit** [vapor/leaf#32]
This does not work :
```
<ul>
    #loop(posts, "post")
    {
        <li>#(post.content)</li>
    }
</ul>
```
This works :
```
<ul>
    #loop(posts, "post") {
        <li>#(post.content)</li>
    }
</ul>
```

**Comment by LoganWright** [comment]
@neospirit sorry about late reply, right now, this is mostly because of design. We're trying to enforce things a bit more strictly to make things easier on parser side and push for some style conventions a bit. We may revisit this at some point to introduce more flexibility.

**Comment by Alex293** [comment]
I can understand that conventions are great to speed up things and keep all clean but I really prefer to use the bracket on the next line when using template files ! I hope this will be allowed in the future. Great job on this renderer tho quick to use/learn
