### ISSUE TITLE
Packages with views

### ISSUE THREAD

**Issue by Casperhr** [vapor/leaf#39]
When building packages with views. You don't want users to copy all the views into their project.
Some of the views would be just fine to have in the package
With the current system this cannot be done

In laravel there was a option to write path as fx
AdminPanel:Login/login

this means it would check if there was a folder in Resources/Views which fitted for /AdminPanel/Login/login.leaf 

if this was not found it would take the same path but in the package

I made a small example of how it could work, but the initialisation with workdir kills it a bit. 

```
 public func makeWithFallback(_ path: String) throws -> View {
        do {
            return try make(Droplet().workDir + "/Resources/Views/" + path)
        } catch {
             return try make(Droplet().workDir + "Packages/AdminPanel-0.1.1/Sources/AdminPanel/Resources/Views/" + path + ".leaf")
        }
        
    }
```

Is this something for next update? It's very handy

**Comment by tannernelson** [comment]
Might be cool if we had an override like:

```
drop.view.make("home", [
    "message": "hi"
], module: AdminPanel.self)
```

**Comment by BrettRToomey** [comment]
I think this would be really nice to have for 2.0. @tanner0101 @LoganWright thoughts?

**Comment by LoganWright** [comment]
We are going to add support in toolbox to export views into a searchable manifest, this keeps things much simpler to reason about and make sure users are getting expected behavior.
