### ISSUE TITLE
Prettier html

### ISSUE THREAD

**Issue by siemensikkema** [vapor/leaf#44]
I noticed two things about the html output of Leaf (there might be others that I have not encountered).

1. there is an extra newline after a loop tag.
2. there does not seem to be a concept of indentation level

This results in html that is perfectly valid but not as pretty to the eye which does not help with debugging.

I have figured out how to solve the first point and I can create a PR if this is helpful. As for the second, I would like to know if this is something people besides me would be interested in. Ideally, any indentation should be able to be turned off as well.

**Comment by LoganWright** [comment]
@siemensikkema this sounds like it would be great, anything we can do to increase development speed is always something we want to add. Especially around debugging, I think having variants like `prettyPrint` and `compact` the way JSON does would be awesome. 

Maintaining indentation levels might be tricky in the parser and lose some performance, but offhand, I think it'd be a valuable feature that we should try to work towards.

For the first one, happy to accept PRs 👍

**Comment by siemensikkema** [comment]
Thanks for the feedback. Good to know we're on the same page :)

See #45 for the PR on removing the newline

**Comment by LoganWright** [comment]
Definitely. Also, if we're developing indentations, tracking line/column numbers would be great for debugging syntax errors.
