### ISSUE TITLE
Declaring variables

### ISSUE THREAD

**Issue by rolandleth** [vapor/leaf#47]
Maybe this is out of Leaf's scope, but coming from `ejs` and `erb`, I thought it would be nice to be able to declare variables (I looked everywhere, and if it's already possible, I missed it every time).

If this isn't possible / is out of scope, what would be a proper way to create and pass a variable to all leafs? It's something for the footer, and the footer is `#imported` everywhere. It would be desirable to not having to create and pass it every time I `view.make`, though 😁

Cheers!

**Comment by tanner0101** [comment]
There are some overloads on `view.make` that accept the request.

See: https://github.com/vapor/vapor/blob/4007f3c7178ba084235c15257a409177f7780e34/Sources/Vapor/View/ViewRenderer%2BRequest.swift

This makes it possible to add global variables like that to the request through middleware. Then just make sure to pass the request to all of your views.

**Comment by rolandleth** [comment]
Thanks for the fast answer! Sadly, I don't think I understand :( 

I'm already passing some variables on a view by view basis, and I'm also using a couple of middlewares in the app, but they only take a request and chain it to a responder, so I'm not really sure how I'd link `view.make` with the middleware's only method. Also, at this point (at the middleware level), I don't even know what view I'll be creating.

I'm a bit confused :)

**Comment by tanner0101** [comment]
When you pass the request into the `drop.view.make` method it will call this method on the request https://github.com/vapor/vapor/blob/257a01d2ee9f2d1f01fc0094ea947506063eeece/Sources/Vapor/HTTP/HTTP%2BNode.swift#L17

Then you can access the request like so:

```swift
drop.get("view") { req in
    return try drop.view.make("form", [
        "name": "Foo"
    ], for: request)
}
```

```leaf
<h1>My Form: #(name)</h1>

#if(request.session.data.user) {
    Welcome #(request.session.data.user.name)
}
```

This example shows using session, but request has a property `storage` that you can add whatever you like to https://github.com/vapor/engine/blob/master/Sources/HTTP/Models/Messages/Message.swift#L56

**Comment by rolandleth** [comment]
Oh, so in any middleware, I should just add the data I want in `storage`, and use it like that? I'll give it a try, thanks!

**Comment by tanner0101** [comment]
Yup. Closing this for now. Feel free to re-open if you have more questions.
