### ISSUE TITLE
layouts

### ISSUE THREAD

**Issue by tannernelson** [vapor/leaf#5]
Take the following code:

```swift
return try drop.view.make("welcome", [
    "name": "Leaf 🍃"
])
```

### Current

Right now we can include leafs into a leaf using `#include` or `#embed`

`welcome.leaf`
```leaf
#embed("header")

<h1>Hello, #(name)</h1>

#embed("footer")
```

### Layouts

We need a way to invert this dependency with layouts by adding three new functions.

- `extend(Constant)`
- `export(Constant) { Body }`
- `import(Constant)`

`welcome.leaf`
```leaf
#extend("app")

#export("main") {
    <h1>Hello, #(name)!</h1>
}
```

`app.leaf`
```leaf
<head>
    <title>my site</title>
</head>

#import("main")

<footer>some copyright crap</footer>
```

or even

`app.leaf`
```leaf
#embed("header")

#import("main")

#embed("footer")
```

**Comment by rugaard** [comment]
It's probably already your plan, but I just didn't see it being mentioned anywhere, so just to be 100% sure I'll request/write it here.

I would very much love to be able to use `#import`, `#export` and `#embed` within each other. I.e. you could have a base layout file, that imports data from "constant". Then in another file, you could extend the base layout and create the exported "constant" that the base layout is expecting.

Example:

`base.leaf`
```html
<!doctype html>
<html>
<head>
    <title>Leaf</title>
</head>
<body>
     #import("content")
</body>
</html>
```

And then in all your other `.leaf` templates you can `#export` data into that template by using `#extend`.

`dashboard.leaf`
```html
#extend("base")

#export("content") {
<h1>Fly with the wind, you beautiful little leaf</h1>
}
```

This could also be an ideal way, to make sure you only import CSS/JS on pages where they are actually used.

`base.leaf`
```html
<body>
     <!-- Content -->
     #import("project-js")
</body>
</html>
```

`dashboard.leaf`
```html
#extend("base")

#export("content") {
<h1>Fly with the wind, you beautiful little leaf</h1>
}

#export("project-js") {
<script src="/chart/library/which/is/only/used/on/the/dashboard.js"></script>
}
```

**Comment by LoganWright** [comment]
One thing I added while I was in there was an optional fallback, for example:

```
*import("header") { Here's a fallback header if no export is found }
```
