### ISSUE TITLE
'#export()' depends on '{' locaiton

### ISSUE THREAD

**Issue by truemetal** [vapor/leaf#52]
Here's a bit of inconsistency in .leaf parsing. You can still get the job done but still it feels like it should not be like that.

This works fine, and renders expected 'Hey'

```
#export("body") {
    <h1>Hey</h1>
}
```

And this renders nothing:

```
#export("body")
{
    <h1>Hey</h1>
}
```

**Comment by tanner0101** [comment]
We should either support unlimited whitespace between `)` and `{` or throw an error

**Comment by 0xTim** [comment]
It also doesn't work without the space, just to add

**Comment by plummer** [comment]
The pr above supports any amount of whitespace, including no whitespace.
