### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by tanner0101** [vapor/leaf#6]
We need to work on creating a universal syntax highlighter for leaf that we can make a Sublime package for and PR into GitHub.

**Comment by LoganWright** [comment]
YES!

**Comment by LoganWright** [comment]
Currently, support is available in Atom provided by @ButkiewiczP

https://atom.io/packages/language-leaf

**Comment by tannernelson** [comment]
I added that to the README.

**Comment by BrettRToomey** [comment]
@tanner0101 @LoganWright status?

**Comment by LoganWright** [comment]
Awesome support added for most text ides.
