### ISSUE TITLE
Feature Request: With-Tag for variable renaming

### ISSUE THREAD

**Issue by fbartho** [vapor/leaf#77]
### Purpose

Sometimes for the purposes of a embedded templates, it would be nice if you could rename variables passed in so that your template is much less clunky. Also, encourages reuse of small chunks of templates.

The with-tag would allow you to use a deeply nested name, as a shorter name within the provided scope.

### Syntax-Suggestion

    #with(<complex.nested.value>, <short-name>, …) { /* template */ }

It accepts N pairs of parameters, where the first of each pair is the context's variable, and the second of each pair is a string of the new name you'd like to use.

### Usage

```html
<!-- Single item rename -->
#with(my.deeply.nested.thing, "myThing") {
    <!--Other columns…--><td>#(myThing.prop)</td><td>#(myThing.anotherProp)</td><td>#(myThing.someOtherProp)</td>
}
<!-- Multiple variable rename -->
#with(
      clunky.obj.name, "name",
      clunky.obj.val, "val",
      clunky-too.foo, "foo"
    ) {
    <ul>#(name): #(val), #(foo)</ul>
}
```

### Impact

- New tag in the leaf-base library. Could conflict if users have implemented this as a custom tag. Documentation burden.
- Shouldn't break any vanilla Leaf apps.
- Simplifies adoption of Leaf as a templating engine.

**Comment by fbartho** [comment]
I have an implementation of this that I tested as a custom-tag in the project I'm building. I'd be happy to contribute that as a PR for comment with this feature request.

**Comment by tanner0101** [comment]
Leaf 3 supports this with `#export("variableName", "value")`

**Comment by fbartho** [comment]
@tanner0101: 
- does `#export` rename multiple things?
- I got leaf2 via vapor, is there a timeline for leaf3 there?

Thanks!

**Comment by tanner0101** [comment]
No timeline yet for Leaf 3. But it's worth noting that you can add custom Leaf commands to your application. Follow [these instructions](https://docs.vapor.codes/2.0/leaf/leaf/#custom-tags) to register them.
