### ISSUE TITLE
#equal(...){...}#else(){...} unreliable

### ISSUE THREAD

**Issue by bottlehall** [vapor/leaf#78]
Hi,

Leaf is pretty incredible, but sometimes #equal(...){...}#else(){...} always instantiates the 'else' content, regardless of the value of the 'equal' condition. For example, this:

`#equal(user.id,"0"){Add New Person} #else(){Edit #(user.forename) #(user.surname)'s Record}`

gives

> Add New Person Edit 's Record

when user.id is equal to zero and:

> Edit Joe Soap's Record

when it isn't

Whereas:

`#equal(role.role,name.role){}#else(){selected="selected"}

works reliably and sets the appropriate option in a drop-down.

The only difference I can see is that the working one is inside a #loop tag and so role.role is a changing value. I have tried making a fixed field user.zero = 0 and putting:

#equal(user.id,user.zero)...

to see if I was doing something wrong with the literal, but it didn't help. I've also tried putting a lot more white space around the tokens, but to no effect.

**Comment by 0xTim** [comment]
@bottlehall for the `else` command you need a double `#`, so it would become `#equal(user.id,"0"){Add New Person} ##else(){Edit #(user.forename) #(user.surname)'s Record}`

The `##` basically means that the next command is chained to the result of the preceding command

**Comment by bottlehall** [comment]
@Tim, thank you for your help. I thought I had tried this, but, of course, you are absolutely correct!

**Comment by 0xTim** [comment]
Things should become a lot simpler in Leaf 3
