### ISSUE TITLE
Boolean Custom Tag always behaves as though result is true

### ISSUE THREAD

**Issue by bottlehall** [vapor/leaf#79]
I have registered a custom tag to return true if the index is odd and false if even as follows:

```
class OddEvenTag: BasicTag {
    let name = "OddEven"

    func run(arguments: ArgumentList) throws -> Node? {
        guard
            arguments.count == 1,
            let index = arguments[0]?.int
            else { return Node(nil) }
        print(index, index & 1)
        return Node((index & 1) == 1)
    }
}
```
The print statement produces satisfyingly good output:

```
0 0
1 1
2 0
3 1
...
```
However, when I use the custom tag inside a #loop in a leaf file, such as

`#OddEven(index){hello}##else(){bye}`

It always instantiates the hello. I've tried hard-coding false into the return statement and it doesn't change the outcome. I have used a (more complex) custom tag before, so I know they can work.

In case you're wondering, I really want to use the tag to alternate the row background colours of a grid!

**Comment by bottlehall** [comment]
If I try just using the tag in this way:

#OddEven(Index)

Then I get 'true' and 'false' correctly included as text in the rendered output. Doesn't get me any nearer it working though!

**Comment by tanner0101** [comment]
That is really strange. Seems as though it should work. Could you create a small, self-contained code sample that exhibits this bug? That will help us track it down.

**Comment by bottlehall** [comment]
I have created a minimal project that demonstrates the problem. The route is /tag.
[minimal.zip](https://github.com/vapor/leaf/files/1476344/minimal.zip)
