### ISSUE TITLE
Leaf 3 - no way to add custom tags

### ISSUE THREAD

**Issue by 0xTim** [vapor/leaf#86]
In Leaf 3 there is currently no easy way to add custom tags. It kinda can be done by overriding the `LeafConfig` in services but if there are multiple providers or instances where this happens, one will always lose. One possibility is to make the `tags` dictionary mutable to allow it to be extended

**Comment by joscdk** [comment]
A lot of packages and projects use custom leaf tags, so this should really be supported :)

**Comment by tanner0101** [comment]
This was made much easier in #89 

```swift
var tags = LeafTagConfig.default()
tags.use(FooTag(), as: "foo")
services.register(tags)
```

**Comment by 0xTim** [comment]
@tanner0101 if multiple packages are registering tags, will this not mean that only one of these packages will have their tags registered?

**Comment by vzsg** [comment]
Maybe these packages should operate on a LeafTagConfig instance instead of Services directly. 🤔

**Comment by Joannis** [comment]
[That's partially fixable](https://github.com/vapor/service/pull/5)

**Comment by tanner0101** [comment]
@0xTim the idea is that providers should only ever _provide_ tags. (i.e., register them to the services struct). It's then up to the user to enable/disable those tags via their config.

```swift
try services.register(TimsTagProvider())

var tags = LeafTagConfig.default()
tags.use(TimsCoolTag.self, as: "foo")
...
services.register(tags)
```

**Comment by 0xTim** [comment]
@tanner0101 just to confirm you are saying it is up to the application to set the tags it wants to use in `LeafTagConfig` rather than the providers registering them for the application? Or are you saying that if I have two provider foo does:

```swift
var tags = LeafTagConfig.default()
tags.use(FooTag.self, as: "foo")
services.register(tags)
```
 and provider bar that does:

```
var tags = LeafTagConfig.default()
tags.use(BarTag.self, as: "bar")
services.register(tags)
```

When an application does:

```swift
try services.register(FooTagProvider())
try services.register(BarTagProvider())
```

Then _**both**_ tags will be registered?

**Comment by tanner0101** [comment]
Sorry that was unclear. The code snippet I pasted was end-user code. Let me include a better example:

Package: "Provider A"
```swift
final class ProvderA {
    func register(services: Services) {
        try services.register {
            return FooTagA()
        }
        try services.register {
            return BarTagA()
        }
    }
}
```

Package: "ProviderB"
```swift
final class ProviderB {
    func register(services: Services) {
        try services.register {
            return BazTagB()
        }
    }
}
```

Package: "App"
```swift
import ProviderA
import ProviderB

var services = Services.default()
try services.register(ProviderA())
try services.register(ProviderB())

var tags = LeafTagConfig.default()
tags.use(FooTagA.self, as "foo")
// use is specifically opting out of using `BarTagA` because they don't want it
tags.use(BazTagB.self, as "baz")
services.register(tags)

// .. continue application code
```

**Comment by 0xTim** [comment]
Hmm my issue with this is that it starts to leak library code into app land. If a library (e.g. SteamPress) wants to use a custom tag (e.g. Markdown) then they have to register it themselves, and it is one more thing to do 🤔

**Comment by 0xTim** [comment]
Though tbf, they have to use the tags in their Leaf files, given they live in app land. Unless a library is generating their own Leaf templates in code rather than using files?

**Comment by tanner0101** [comment]
This is a much bigger question w/ how the `Service` module works in general. The module is designed to give all configuration options to the user (no services should be automatically used that the user did not explicitly register or configure). A system on top of this for automatically configuring things could make sense, although it is quite easy currently for a package to _extend_ things like `LeafTagConfig` with convenience methods. For example:

```
var tags = LeafTagConfig.default()
tags.enabledAllStreamPressTags()
```

Closing this issue since it's too late in the game to make a big change to the services architecture for Vapor 3. Nonetheless, we should make sure to keep an eye on how services works this release and re-open discussions for Vapor 4.
