### ISSUE TITLE
#loop in one line

### ISSUE THREAD

**Issue by AndriyGo** [vapor/leaf#93]
Currently, code below:

```html
<ul class="sidenav" id="mobile-demo">#loop(menu, "item"){<li><a href=#(item.href)>#(item.title)</a></li>}</ul>
```

Produces such output:
```html
<ul class="sidenav" id="mobile-demo"><li><a href=ITEM1_HREF)>ITEM1_TITLE</a></li>
<li><a href=ITEM2_HREF)>ITEM2_TITLE</a></li>
<li><a href=ITEM3_HREF)>ITEM3_TITLE</a></li></ul>
```

For those who are obsessed with minifying html it would be great if it could produce:

```html
<ul class="sidenav" id="mobile-demo"><li><a href=ITEM1_HREF)>ITEM1_TITLE</a></li><li><a href=ITEM2_HREF)>ITEM2_TITLE</a></li><li><a href=ITEM3_HREF)>ITEM3_TITLE</a></li></ul>
```

i.e. everything in one line

**Comment by 0xTim** [comment]
@AndriyGo you can probably write a custom tag (that is a clone of the original) that doesn't add the new line in. The risk of doing it with loop is that people may not be wrapping their items in any tags so would just get `Item1Item2Item3` in their HTML

**Comment by AndriyGo** [comment]
@0xTim Could you please elaborate on how I could create such custom tag? This solution would work for me.

However, in general, I do not entirely agree that adding extra space/new line helps. Loops in any other environment do not exhibit such behaviour, and it is up to the developer to control whether the output is printed in one line or not. As a possible resolution, there could be an option to opt in/out of such behaviour, although I do understand that it would probably be too much work for too little benefit :)

Anyway, as I said, any workaround will work for me.

**Comment by tanner0101** [comment]
This should work fine in Leaf 3.0. No extra line breaks should get added in the for-loop implementation.
